const express = require('express');
const r = express.Router();
const { createRazorpayOrder, verifyPayment, handleWebhook } = require('../controllers/paymentController');
const { protect } = require('../middleware/authMiddleware');
const validate = require('../middleware/validate');
const { paymentSchemas } = require('../validators');
r.post('/create-order', protect, validate(paymentSchemas.createOrder), createRazorpayOrder);
r.post('/verify', protect, validate(paymentSchemas.verify), verifyPayment);
r.post('/webhook', handleWebhook);
module.exports = r;
