const express = require('express');
const r = express.Router();
const { createReview, getProductReviews, deleteReview } = require('../controllers/reviewController');
const { protect } = require('../middleware/authMiddleware');
const validate = require('../middleware/validate');
const { reviewSchemas } = require('../validators');
r.post('/', protect, validate(reviewSchemas.create), createReview);
r.get('/:productId', getProductReviews);
r.delete('/:id', protect, deleteReview);
module.exports = r;
